### ISSUE TITLE
readlink command missing '-f' in binstub?

### ISSUE THREAD

**Issue by ringods** [test-kitchen/busser#12]
I'm having problems with the generated binstub after running ``busser setup`` (part of ``kitchen verify``). In [one of my Wercker box repositories](https://github.com/AutomateDev/box-chef-dk), I install chef-dk and some plugins, followed by running serverspec to validate correct installation by checking the command line versions.

I install busser on a system ruby since [it doesn't support Chef-DK yet](https://github.com/test-kitchen/test-kitchen/issues/443). Since upgrading my base OS from Ubuntu 12.04 to 14.04, the binstub fails, because of a different setup of the ruby softlinks:

Ubuntu 12.04:
```
ubuntu@ip-10-209-166-44:~$ ls -l /usr/bin/ruby
lrwxrwxrwx 1 root root 22 Sep 14 16:26 /usr/bin/ruby -> /etc/alternatives/ruby
ubuntu@ip-10-209-166-44:~$ ls -l /etc/alternatives/ruby
lrwxrwxrwx 1 root root 18 Sep 14 16:26 /etc/alternatives/ruby -> /usr/bin/ruby1.9.1
ubuntu@ip-10-209-166-44:~$ SOURCE=/usr/bin/ruby
ubuntu@ip-10-209-166-44:~$ while [ -h "$SOURCE" ] ; do SOURCE="`readlink "$SOURCE"`"; done
ubuntu@ip-10-209-166-44:~$ dirname $SOURCE
/usr/bin
ubuntu@ip-10-209-166-44:~$ echo $SOURCE
/usr/bin/ruby1.9.1
```

Ubuntu 14.04:
```
ubuntu@ip-10-209-52-131:~$ ls -l /usr/bin/ruby
lrwxrwxrwx 1 root root 9 Feb 15  2014 /usr/bin/ruby -> ruby1.9.1
ubuntu@ip-10-209-52-131:~$ SOURCE="/usr/bin/ruby"
ubuntu@ip-10-209-52-131:~$ while [ -h "$SOURCE" ] ; do SOURCE="`readlink "$SOURCE"`"; done
ubuntu@ip-10-209-52-131:~$ dirname $SOURCE
.
ubuntu@ip-10-209-52-131:~$ echo $SOURCE
ruby1.9.1
```

Adding the ``-f`` option to the ``readlink`` command solves my problem, but I'm not sure if this option is supported on all the different Unix flavors.

Comments?

**Comment by fnichol** [comment]
Hi @ringods, sorry this took so long to address.

As of ca17639694d275e17fc8f08b555e2522a82768dd, the directory de-referencing is removed in an attempt to increase this binstub's portability. I'll be releasing Busser shortly to close this out.

**Comment by fnichol** [comment]
Release 0.7.0 just went out, eliminating the code in the Busser binstub that had the calls to `readlink`.
