### ISSUE TITLE
Testing LWRPs, not recipes

### ISSUE THREAD

**Issue by promisedlandt** [test-kitchen/busser#16]
Fletcher,
thank you for test-kitchen.

Is there any way to test LWRPs instead of recipes?  
I looked at the busser-minitest source code, and it's not supported there.  
My "dream functionality" would be to to test a single LWRP multiple times with different attributes.  

I understand I could create a test recipe for each LWRP invocation, but that does not seem like a good solution.

**Comment by callmeradical** [comment]
Why not step_into the lwrp?

**Comment by promisedlandt** [comment]
Isn't that a ChefSpec only thing?

**Comment by callmeradical** [comment]
Oh I am sorry, I completely jumped over the minitest piece. We started using ChefSpec specifically because of this.

**Comment by cheeseplus** [comment]
This is exactly what fixture cookbooks are for - see the examples under the mysql cookbook https://github.com/chef-cookbooks/mysql/tree/master/test/fixtures/cookbooks
