### ISSUE TITLE
kitchen test with serverspec fails: `run_ruby_script!': undefined method `success?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tknerr** [test-kitchen/busser#17]
As per suggestion of @cl-lab-k I forwarded the original issue (test-kitchen/busser-serverspec#22) here.

In my scenario `kitchen test` reproducably fails on the first run, but succeeds on subsequent runs. See description in the original issue for more details.

Any ideas?

**Comment by fnichol** [comment]
For anyone interested, I updated test-kitchen/busser-serverspec#22 with a status update.
