### ISSUE TITLE
Add a busser for testinfra

### ISSUE THREAD

**Issue by jtimberman** [test-kitchen/busser#28]
Testinfra is a new project featured in this weeks DevOps Weekly newsletter. It may be useful to have a busser for it. It's alpha software.

- https://github.com/philpep/testinfra
- http://testinfra.readthedocs.org/en/latest/

@fnichol I didn't know where the best place to open this issue is, so feel free to reopen elsewhere if there's a better project for tracking this. :ice_cream:

**Comment by doertedev** [comment]
:+1:

**Comment by cheeseplus** [comment]
If someone wants to write this I'm more than happy to let it live in the test-kitchen organization but we've no plans to add this as we've more than plenty to triage on the existing projects. 

tl;dr This is going to be very, very low on the core team's priority

**Comment by jcftang-r7** [comment]
FYI -- https://github.com/jcftang-r7/busser-testinfra I've only recently put this together and it's just enough for what I want to do.

**Comment by cheeseplus** [comment]
Great work @jcftang-r7 - I'm going to close this issue now that this exists and point people that way should they ask!
